{
    'name': "MES COLLEGE",
    'summary': """
       MES KALLADI COLLEGE OF ARTS AND SCIENCE""",
    'author': " Mincetech",
    'license': 'LGPL-3',
    'category': "Theme",
    'version': "16.0.1.0.0",
    'sequence': "1",
    'installable': True,
    'application': True,
    'auto_install': False,
    'depends': [
        'website',
        'base_setup',
        'web',
        'embase_portal_api_integration',
    ],
    'data': [
        'views/res_config_settings.xml',
        'views/mes_header.xml',
        'views/departments.xml',
        'views/mes_index.xml',
        'views/mes_views.xml',
        'views/mes_footer.xml',
        'views/outreach.xml',
        'views/achievements.xml',
        'views/gallery.xml',
        'views/news_detail.xml',
        'views/no_data.xml',
        'views/news_events.xml',
        'views/programme_detail.xml',
        'views/upcoming_activity_detail.xml',
        'views/clubs.xml',
        'views/clubs_page.xml',

        'views/departments/activities_detail.xml',
        'views/departments/department_activities.xml',
        'views/departments/department_faculties.xml',
        'views/departments/department_gallery.xml',
        'views/departments/department_page.xml',
        'views/departments/department_programmes.xml',
        'views/departments/faculty_profile.xml',
        'views/departments/department_facilities.xml',
        'views/departments/department_projects.xml',
        'views/departments/department_exam_results.xml',
        'views/departments/exam_results_view.xml',
        'views/departments/department_reports.xml',

        'views/about_mes/about.xml',
        'views/about_mes/vision_mission.xml',
        'views/about_mes/milestone.xml',
        'views/about_mes/management.xml',
        'views/about_mes/college_prayer.xml',
        'views/about_mes/college_crest.xml',
        'views/about_mes/quality_policy.xml',
        'views/about_mes/perspective.xml',
        'views/about_mes/brief_history.xml',
        'views/about_mes/strategic_plan.xml',
        'views/about_mes/principal.xml',
        'views/about_mes/principal_profile.xml',
        'views/about_mes/college_council.xml',
        'views/about_mes/club_coordinators.xml',
        'views/about_mes/administrative_staff.xml',
        'views/about_mes/code_of_conduct_students.xml',
        'views/about_mes/resource_mobilization.xml',
        'views/about_mes/code_of_conduct_staff.xml',
        'views/about_mes/nirf.xml',
        'views/about_mes/aishe.xml',
        'views/about_mes/ariia.xml',
        'views/about_mes/planning_board.xml',
        'views/about_mes/governing_body.xml',
        'views/about_mes/environmental_policy.xml',
        'views/about_mes/former_principals.xml',
        'views/about_mes/planning_board.xml',
        'views/about_mes/governing_body.xml',
        'views/about_mes/roll_of_honors.xml',
        'views/about_mes/organogram.xml',

        'views/academics/programmes.xml',
        'views/academics/programmes_details.xml',
        'views/academics/evaluation_policy.xml',
        'views/academics/academic_calendar.xml',
        'views/academics/academic_monitoring_cell.xml',

        'views/research/res-chemistry.xml',
        'views/research/res-history.xml',
        'views/research/res-economics.xml',
        'views/research/res-facilities.xml',
        'views/research/research-promotion-council.xml',
        'views/research/research-guides.xml',
        'views/research/research-projects.xml',
        'views/research/research-publications.xml',
        'views/research/research-publications_faculty.xml',
        'views/research/code_of_ethics.xml',
        'views/research/ipr_cell.xml',
        'views/research/plagiarism_policy.xml',
        'views/research/seminars-workshops.xml',

        'views/iqac/iqac_objectives.xml',
        'views/iqac/composition.xml',
        'views/iqac/aqar.xml',
        'views/iqac/minutes.xml',
        'views/iqac/annual_reports.xml',
        'views/iqac/action_take_report.xml',
        'views/iqac/academic_auditing.xml',
        'views/iqac/iqac_activities.xml',
        'views/iqac/naac.xml',
        'views/iqac/naac_certificates.xml',
        'views/iqac/margadarshan.xml',
        'views/iqac/iqac_best_practices.xml',
        'views/iqac/alumni_feed.xml',
        'views/iqac/students_feed.xml',
        'views/iqac/employer_feed.xml',
        'views/iqac/teachers_feed.xml',
        'views/iqac/ssr_documents.xml',

        'views/statutory_cell/anti_ragging_cell.xml',
        'views/statutory_cell/anti_sexual_harassment_cell.xml',
        'views/statutory_cell/minority_cell.xml',
        'views/statutory_cell/obc_cell.xml',
        'views/statutory_cell/sc_st_cell.xml',
        'views/statutory_cell/students_grievance_redressal_cell.xml',

        'views/admission/admission_procedure.xml',
        'views/admission/prospectus.xml',
        'views/admission/rules_and_regulations.xml',
        'views/admission/fee_structure.xml',
        'views/admission/distribution_seats.xml',
        'views/admission/cut_of_marks.xml',

        'views/student_corner/scholarships.xml',
        'views/student_corner/capacity_building_programmes.xml',
        'views/student_corner/civil_service_academy.xml',
        'views/student_corner/counselling.xml',
        'views/student_corner/ncc.xml',
        'views/student_corner/nptel_local.xml',
        'views/student_corner/nss.xml',
        'views/student_corner/skill_tune.xml',
        'views/student_corner/technology_business.xml',
        'views/student_corner/udyami.xml',
        'views/student_corner/pta.xml',
        'views/student_corner/facilitation_centres.xml',
        'views/student_corner/student_union.xml',
        'views/student_corner/career_guidance_placement.xml',
        'views/facilities/academic_facilities.xml',
        'views/facilities/auditorium.xml',
        'views/facilities/campus_amenities.xml',
        'views/facilities/hostel.xml',
        'views/facilities/ict_labs.xml',
        'views/facilities/laboratories.xml',
        'views/facilities/sports_infrastructure.xml',
        'views/library/library.xml',
        'views/library/library_e_resources.xml',

        'views/alumni/alumni_associate.xml',
        'views/alumni/alumni_registration.xml',
        'views/alumni/distinguished_alumni.xml',

        'views/ssr/ssr_home.xml',

        'views/ssr/curricular_aspects/add-on-certificate-value.xml',
        'views/ssr/curricular_aspects/curricular_planning.xml',
        'views/ssr/curricular_aspects/feedback_dvv.xml',
        'views/ssr/curricular_aspects/feedback_system.xml',
        'views/ssr/curricular_aspects/integrates-crosscutting-issues.xml',
        'views/ssr/curricular_aspects/percentage-of-students-enrolled.xml',
        'views/ssr/curricular_aspects/percentage-of-students-enrolled_dvv.xml',
        'views/ssr/curricular_aspects/project-field-work-internships.xml',

        'views/ssr/infrastructure_learning_resources/adequate_infrastructure.xml',
        'views/ssr/infrastructure_learning_resources/campus_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/infrastructure_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/it_facilities.xml',
        'views/ssr/infrastructure_learning_resources/library_automated.xml',
        'views/ssr/infrastructure_learning_resources/percentage_of_expenditure.xml',
        'views/ssr/infrastructure_learning_resources/percentage_of_expenditure_incurred.xml',
        'views/ssr/infrastructure_learning_resources/physical_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/student_computer_ratio.xml',

        'views/ssr/student_support_progression/alumni_association.xml',
        'views/ssr/student_support_progression/capacity_building.xml',
        'views/ssr/student_support_progression/cultural_programs.xml',
        'views/ssr/student_support_progression/guidance_for_competitive.xml',
        'views/ssr/student_support_progression/outstanding_performance.xml',
        'views/ssr/student_support_progression/percentage_of_placement.xml',
        'views/ssr/student_support_progression/scholarships_and_free_ships.xml',
        'views/ssr/student_support_progression/state_national.xml',
        'views/ssr/student_support_progression/support_dvv_clarification.xml',
        'views/ssr/student_support_progression/support_dvv_clarification2.xml',
        'views/ssr/student_support_progression/transparent_mechanism.xml',

        'views/ssr/best_practices/best-practices.xml',
        'views/ssr/best_practices/efforts_initiatives.xml',
        'views/ssr/best_practices/energy_regularly.xml',
        'views/ssr/best_practices/institution_initiatives.xml',
        'views/ssr/best_practices/portray_performance.xml',
        'views/ssr/best_practices/promotion_gender.xml',

        'views/ssr/governance_leadership_management/financial_dvv_clarification.xml',
        'views/ssr/governance_leadership_management/financial_support.xml',
        'views/ssr/governance_leadership_management/governance_vision.xml',
        'views/ssr/governance_leadership_management/implementation_e-governance.xml',
        'views/ssr/governance_leadership_management/institutional_bodies.xml',
        'views/ssr/governance_leadership_management/internal_quality_assurance.xml',
        'views/ssr/governance_leadership_management/mobilization_optimal.xml',
        'views/ssr/governance_leadership_management/non_teaching_staff.xml',
        'views/ssr/governance_leadership_management/quality_assurance.xml',
        'views/ssr/governance_leadership_management/strategy_dvv_clarification.xml',
        'views/ssr/governance_leadership_management/welfare_measures.xml',

        'views/ssr/research_innovations_extension/awards_and_recognitions.xml',
        'views/ssr/research_innovations_extension/collaboration_dvv_clarification.xml',
        'views/ssr/research_innovations_extension/ecosystem_for_innovations.xml',
        'views/ssr/research_innovations_extension/extension_activities_carried.xml',
        'views/ssr/research_innovations_extension/grants_received.xml',
        'views/ssr/research_innovations_extension/mous_collaboration.xml',
        'views/ssr/research_innovations_extension/number-of-extension.xml',
        'views/ssr/research_innovations_extension/number_of_books.xml',
        'views/ssr/research_innovations_extension/number_of_research_papers.xml',
        'views/ssr/research_innovations_extension/workshops_seminars_conferences.xml',

        'views/ssr/teaching_learning_and_valuation/enrolment-percentage.xml',
        'views/ssr/teaching_learning_and_valuation/full-time-teachers.xml',
        'views/ssr/teaching_learning_and_valuation/full-time-teachers-highest-degree.xml',
        'views/ssr/teaching_learning_and_valuation/mechanism_of_assessment.xml',
        'views/ssr/teaching_learning_and_valuation/pass_percentage.xml',
        'views/ssr/teaching_learning_and_valuation/programme_outcomes.xml',
        'views/ssr/teaching_learning_and_valuation/reserved-seats-filled.xml',
        'views/ssr/teaching_learning_and_valuation/student-centric-methods.xml',
        'views/ssr/teaching_learning_and_valuation/student-centric-methods.xml',
        'views/ssr/teaching_learning_and_valuation/student-full-time-teacher-ratio.xml',
    ],
    'assets': {

        'web.assets_frontend': [
            'mes_college/static/src/css/mes.min.css',
            'mes_college/static/src/css/quill.css',
            'mes_college/static/src/js/tab_active.js',
            'mes_college/static/src/js/carousel_active.js',
        ],
    },

}
