{
    'name': "EMEA COLLEGE THEME",
    'summary': """
       EMEA COLLEGE THEME""",
    'description': """
        Long description of module's purpose
    """,
    'author': " Mincetech",
    'license': 'LGPL-3',
    'category': "Theme",
    'version': "16.0.1.0.0",
    'sequence': "1",
    'installable': True,
    'application': True,
    'auto_install': False,
    'depends': [
        'website',
        'web',
        'base_setup',
        'embase_portal_api_integration',
    ],
    'data': [
        'views/emea_header.xml',
        # 'views/emea_index.xml',
        'views/footer.xml',
        'views/emea_college_home.xml',
        'views/document_saving.xml',
        'views/emea_views.xml',

        'views/about/history.xml',
        'views/about/vision_mission.xml',
        'views/about/college_emblem.xml',
        'views/about/principal.xml',
        'views/about/principal_profile.xml',
        'views/about/former_principals.xml',
        'views/about/management.xml',
        'views/about/pta.xml',
        'views/about/staff_council.xml',

        'views/studentzone/nss.xml',
        'views/studentzone/ncc.xml',
        'views/studentzone/administrative_staff.xml',
        'views/studentzone/clubs.xml',
        'views/studentzone/student_support.xml',
        'views/studentzone/scholarships.xml',
        'views/studentzone/student_descipline.xml',
        'views/studentzone/student_union.xml',
        'views/studentzone/capability_enhancement.xml',
        'views/studentzone/college_magazine.xml',

        'views/academics/academic_calendar.xml',
        'views/academics/academics.xml',
        'views/academics/programmes.xml',
        'views/academics/certificate_courses.xml',

        'views/research/code_of_ethics.xml',
        'views/research/publications.xml',
        'views/research/research_committee.xml',
        'views/research/research_depts.xml',
        'views/research/research_projects.xml',
        'views/research/research_scholars.xml',
        'views/research/seminars.xml',

        'views/departments/department_pages.xml',
        'views/departments/economics.xml',
        'views/departments/english.xml',
        'views/departments/b_voc_islamic_finance.xml',
        'views/departments/b_voc_logistics_management.xml',
        'views/departments/b_voc_professional_accounting.xml',
        'views/departments/biochemistry.xml',
        'views/departments/biotechnology.xml',
        'views/departments/business_administration.xml',
        'views/departments/commerce.xml',
        'views/departments/computer_science.xml',
        'views/departments/mathematics_and_physics.xml',
        'views/departments/microbiology.xml',
        'views/departments/west_asian_studies.xml',
        'views/departments/staffprofile.xml',

        'views/iqac/composition_iqac.xml',
        'views/iqac/function_objectives.xml',
        'views/iqac/minutes_atr.xml',
        'views/iqac/iqac_annual_report.xml',
        'views/iqac/aaa.xml',
        'views/iqac/aishe.xml',
        'views/iqac/api.xml',
        'views/iqac/aqar.xml',
        'views/iqac/ariia.xml',
        'views/iqac/best_practices.xml',
        'views/iqac/curriculum_feedback.xml',
        'views/iqac/energy.xml',
        'views/iqac/gender.xml',
        'views/iqac/general.xml',
        'views/iqac/green.xml',
        'views/iqac/institutional_distinctiveness.xml',
        'views/iqac/nirf.xml',
        'views/iqac/ssr.xml',
        'views/iqac/sss.xml',
        'views/iqac/sss_annual_report.xml',
        'views/iqac/stakeholders.xml',
        'views/iqac/workshops.xml',
        'views/iqac/employer.xml',
        # 'views/iqac/aqar-documents.xml',
        'views/iqac/iqac_activities.xml',
        'views/iqac/curriculum_feedback_atr.xml',
        'views/iqac/gender_equity.xml',
        'views/iqac/mandatory_disclosure.xml',
        'views/iqac/aqar-page.xml',

        'views/facilities/laboratories.xml',
        'views/facilities/academics_support.xml',
        'views/facilities/eco_friendly.xml',
        'views/facilities/general_facilities.xml',
        'views/facilities/hostels-retiring-rooms.xml',
        'views/facilities/sports_game.xml',

        'views/mhrd/mhrd_aishe.xml',
        'views/mhrd/ariia.xml',
        'views/mhrd/mgncre.xml',
        'views/mhrd/nirf.xml',
        'views/mhrd/pfms.xml',
        'views/mhrd/rusa.xml',
        'views/mhrd/ugc.xml',

        'views/alumni/library_members.xml',
        'views/alumni/osaemea.xml',
        'views/alumni/osaemea_chapter.xml',

        'views/ssr/ssr_home.xml',

        'views/ssr/curricular_aspects/add-on-certificate-value.xml',
        'views/ssr/curricular_aspects/curricular_planning.xml',
        'views/ssr/curricular_aspects/feedback_dvv.xml',
        'views/ssr/curricular_aspects/feedback_system.xml',
        'views/ssr/curricular_aspects/integrates-crosscutting-issues.xml',
        'views/ssr/curricular_aspects/percentage-of-students-enrolled.xml',
        'views/ssr/curricular_aspects/percentage-of-students-enrolled_dvv.xml',
        'views/ssr/curricular_aspects/project-field-work-internships.xml',

        'views/ssr/infrastructure_learning_resources/adequate_infrastructure.xml',
        'views/ssr/infrastructure_learning_resources/campus_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/infrastructure_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/it_facilities.xml',
        'views/ssr/infrastructure_learning_resources/library_automated.xml',
        'views/ssr/infrastructure_learning_resources/percentage_of_expenditure.xml',
        'views/ssr/infrastructure_learning_resources/percentage_of_expenditure_incurred.xml',
        'views/ssr/infrastructure_learning_resources/physical_dvv_clarification.xml',
        'views/ssr/infrastructure_learning_resources/student_computer_ratio.xml',

        'views/ssr/student_support_progression/alumni_association.xml',
        'views/ssr/student_support_progression/capacity_building.xml',
        'views/ssr/student_support_progression/cultural_programs.xml',
        'views/ssr/student_support_progression/guidance_for_competitive.xml',
        'views/ssr/student_support_progression/outstanding_performance.xml',
        'views/ssr/student_support_progression/percentage_of_placement.xml',
        'views/ssr/student_support_progression/scholarships_and_free_ships.xml',
        'views/ssr/student_support_progression/state_national.xml',
        'views/ssr/student_support_progression/support_dvv_clarification.xml',
        'views/ssr/student_support_progression/support_dvv_clarification2.xml',
        'views/ssr/student_support_progression/transparent_mechanism.xml',

        'views/ssr/best_practices/best-practices.xml',
        'views/ssr/best_practices/efforts_initiatives.xml',
        'views/ssr/best_practices/energy_regularly.xml',
        'views/ssr/best_practices/institution_initiatives.xml',
        'views/ssr/best_practices/portray_performance.xml',
        'views/ssr/best_practices/promotion_gender.xml',

        'views/ssr/governance_leadership_management/financial_dvv_clarification.xml',
        'views/ssr/governance_leadership_management/financial_support.xml',
        'views/ssr/governance_leadership_management/governance_vision.xml',
        'views/ssr/governance_leadership_management/implementation_e-governance.xml',
        'views/ssr/governance_leadership_management/institutional_bodies.xml',
        'views/ssr/governance_leadership_management/internal_quality_assurance.xml',
        'views/ssr/governance_leadership_management/mobilization_optimal.xml',
        'views/ssr/governance_leadership_management/non_teaching_staff.xml',
        'views/ssr/governance_leadership_management/quality_assurance.xml',
        'views/ssr/governance_leadership_management/strategy_dvv_clarification.xml',
        'views/ssr/governance_leadership_management/welfare_measures.xml',

        'views/ssr/research_innovations_extension/awards_and_recognitions.xml',
        'views/ssr/research_innovations_extension/collaboration_dvv_clarification.xml',
        'views/ssr/research_innovations_extension/ecosystem_for_innovations.xml',
        'views/ssr/research_innovations_extension/extension_activities_carried.xml',
        'views/ssr/research_innovations_extension/grants_received.xml',
        'views/ssr/research_innovations_extension/mous_collaboration.xml',
        'views/ssr/research_innovations_extension/number-of-extension.xml',
        'views/ssr/research_innovations_extension/number_of_books.xml',
        'views/ssr/research_innovations_extension/number_of_research_papers.xml',
        'views/ssr/research_innovations_extension/workshops_seminars_conferences.xml',

        'views/ssr/teaching_learning_and_valuation/enrolment-percentage.xml',
        'views/ssr/teaching_learning_and_valuation/full-time-teachers.xml',
        'views/ssr/teaching_learning_and_valuation/full-time-teachers-highest-degree.xml',
        'views/ssr/teaching_learning_and_valuation/mechanism_of_assessment.xml',
        'views/ssr/teaching_learning_and_valuation/pass_percentage.xml',
        'views/ssr/teaching_learning_and_valuation/programme_outcomes.xml',
        'views/ssr/teaching_learning_and_valuation/reserved-seats-filled.xml',
        'views/ssr/teaching_learning_and_valuation/student-centric-methods.xml',
        'views/ssr/teaching_learning_and_valuation/student-full-time-teacher-ratio.xml',

    ],
    'assets': {
        'web.assets_frontend': [
            'emea_college_theme/static/src/css/emea.css',
            'emea_college_theme/static/src/js/emea_header.js',
            'emea_college_theme/static/src/js/download-doc.js',
            'emea_college_theme/static/src/js/dropdown-collapse.js',
            'emea_college_theme/static/src/js/menu_items_width.js',
            'emea_college_theme/static/src/js/mobile-button.js',
            'emea_college_theme/static/src/js/mobile-navbar.js',
            'emea_college_theme/static/src/js/nav-toggler.js',
            'emea_college_theme/static/src/js/page_url_change.js',
            'emea_college_theme/static/src/js/search.js',
            'emea_college_theme/static/src/js/site-navigation-load.js',
            'emea_college_theme/static/src/js/tablist.js',
            'emea_college_theme/static/src/js/tablist-scroll.js',
        ],
    },

}
