from . import landing_page
from . import placement
from . import gallery
from . import student_voice
from . import news_letter
from . import department
from . import department_club_line
from . import user_dep_id
from . import career
from . import notes
from . import academic_calendar
from . import clubs
from . import cells
from . import associations
from . import pta
from . import facilities